### ISSUE TITLE
Allow usage of custom CA bundles

### ISSUE THREAD

**Issue by schakko** [dreitier/backmon#16]
As suggested by @thomashoell, *backmon* should support custom CA bundles when connecting to custom S3 endpoint (e.g. Minio).
Maybe the usage of `AWS_CA_BUNDLE` is sufficient, see https://github.com/aws/aws-sdk-go/issues/3618.

**Comment by thomashoell** [comment]
Is resolved in the chart (https://github.com/dreitier/helm-charts/commit/265df036db7ee1fcc6dc8bed85a57778c01695dc)
